# Generated by Django 6.0.3 on 2026-04-21 07:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_tu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diem_den', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nhan_xep_loai', models.CharField(max_length=50)),
                ('kich_hoat', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-diem_tu'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hp', models.CharField(max_length=20, unique=True)),
                ('ten_hp', models.CharField(max_length=150)),
                ('so_tin_chi', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'ordering': ['ma_hp'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sv', models.CharField(max_length=20, unique=True)),
                ('ho_ten', models.CharField(max_length=150)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20)),
                ('khoa', models.CharField(max_length=120)),
                ('nganh', models.CharField(max_length=120)),
                ('lop', models.CharField(max_length=50)),
                ('khoa_hoc', models.CharField(max_length=30)),
                ('trang_thai', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOFT_DELETED', 'Soft deleted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ma_sv'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(max_length=120)),
                ('doi_tuong', models.CharField(max_length=120)),
                ('truoc_thay_doi', models.JSONField(blank=True, null=True)),
                ('sau_thay_doi', models.JSONField(blank=True, null=True)),
                ('tao_luc', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tao_luc'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ky', models.CharField(max_length=10)),
                ('nam_hoc', models.CharField(max_length=20)),
                ('trang_thai', models.CharField(choices=[('DANG_HOC', 'Dang hoc'), ('HOAN_THANH', 'Hoan thanh'), ('HUY', 'Huy')], default='DANG_HOC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-nam_hoc', '-hoc_ky', 'course__ma_hp'],
            },
        ),
        migrations.CreateModel(
            name='AcademicStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa_tich_luy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('xep_loai', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_standing', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DAO_TAO', 'Dao tao'), ('GIANG_VIEN', 'Giang vien'), ('CO_VAN', 'Co van hoc tap')], default='DAO_TAO', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_qua_trinh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diem_thi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diem_tong_ket_10', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('diem_he_4', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('diem_chu', models.CharField(blank=True, max_length=2)),
                ('lan_hoc', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.enrollment')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'lan_hoc'), name='uniq_enrollment_attempt')],
            },
        ),
        migrations.CreateModel(
            name='GPASemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ky', models.CharField(max_length=10)),
                ('nam_hoc', models.CharField(max_length=20)),
                ('gpa_he_4', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('tong_tin_chi_tich_luy', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_semesters', to='students.student')),
            ],
            options={
                'ordering': ['-nam_hoc', '-hoc_ky'],
                'constraints': [models.UniqueConstraint(fields=('student', 'hoc_ky', 'nam_hoc'), name='uniq_student_semester_snapshot')],
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'hoc_ky', 'nam_hoc'), name='uniq_student_course_semester_year'),
        ),
    ]
