# Generated by Django 6.0.3 on 2026-04-21 09:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='diem_chuyen_can',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='trang_thai',
            field=models.CharField(choices=[('DANG_HOC', 'Đang học'), ('HOAN_THANH', 'Hoàn thành'), ('HUY', 'Hủy')], default='DANG_HOC', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='trang_thai',
            field=models.CharField(choices=[('ACTIVE', 'Đang học'), ('INACTIVE', 'Tạm ngưng'), ('SOFT_DELETED', 'Đã xóa mềm')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('DAO_TAO', 'Đào tạo'), ('GIANG_VIEN', 'Giảng viên'), ('CO_VAN', 'Cố vấn học tập')], default='DAO_TAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Không hoạt động'), ('LOCKED', 'Bị khóa')], default='ACTIVE', max_length=20),
        ),
    ]
