# Generated by Django 6.0.3 on 2026-04-23 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_roles(apps, schema_editor):
    UserProfile = apps.get_model("students", "UserProfile")
    role_mapping = {
        "DAO_TAO": "ADMIN",
        "CO_VAN": "GIANG_VIEN",
    }
    for old_role, new_role in role_mapping.items():
        UserProfile.objects.filter(role=old_role).update(role=new_role)


def backfill_classroom_for_enrollments(apps, schema_editor):
    UserProfile = apps.get_model("students", "UserProfile")
    Classroom = apps.get_model("students", "Classroom")
    Enrollment = apps.get_model("students", "Enrollment")

    active_teacher = UserProfile.objects.filter(role="GIANG_VIEN", status="ACTIVE").order_by("id").first()
    default_teacher_id = active_teacher.user_id if active_teacher else None

    existing_codes = set(Classroom.objects.values_list("ma_lop_hp", flat=True))
    key_to_classroom_id: dict[tuple[int, str, str], int] = {}

    enrollments = Enrollment.objects.filter(classroom__isnull=True).order_by("id")
    for enrollment in enrollments:
        key = (enrollment.course_id, enrollment.hoc_ky, enrollment.nam_hoc)
        classroom_id = key_to_classroom_id.get(key)

        if classroom_id is None:
            base_code = f"AUTO-{enrollment.course_id}-{enrollment.hoc_ky}-{enrollment.nam_hoc.replace('-', '')}"
            candidate = base_code[:30]
            suffix = 1
            while candidate in existing_codes:
                suffix += 1
                suffix_text = f"-{suffix}"
                candidate = f"{base_code[: 30 - len(suffix_text)]}{suffix_text}"

            classroom = Classroom.objects.create(
                ma_lop_hp=candidate,
                course_id=enrollment.course_id,
                giang_vien_id=default_teacher_id,
                hoc_ky=enrollment.hoc_ky,
                nam_hoc=enrollment.nam_hoc,
                phong_hoc="",
                lich_hoc="",
                si_so_toi_da=200,
                trang_thai="OPEN",
            )
            existing_codes.add(candidate)
            classroom_id = classroom.id
            key_to_classroom_id[key] = classroom_id

        enrollment.classroom_id = classroom_id
        enrollment.save(update_fields=["classroom"])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_grade_diem_chuyen_can_alter_enrollment_trang_thai_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_profile', to='students.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='trang_thai',
            field=models.CharField(choices=[('DANG_HOC', 'Dang hoc'), ('HOAN_THANH', 'Hoan thanh'), ('HUY', 'Huy')], default='DANG_HOC', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='trang_thai',
            field=models.CharField(choices=[('ACTIVE', 'Dang hoc'), ('INACTIVE', 'Tam ngung'), ('SOFT_DELETED', 'Da xoa mem')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quan tri vien'), ('SINH_VIEN', 'Sinh vien'), ('GIANG_VIEN', 'Giang vien')], default='SINH_VIEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoat dong'), ('INACTIVE', 'Khong hoat dong'), ('LOCKED', 'Bi khoa')], default='ACTIVE', max_length=20),
        ),
        migrations.RunPython(migrate_legacy_roles, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop_hp', models.CharField(max_length=30, unique=True)),
                ('hoc_ky', models.CharField(max_length=10)),
                ('nam_hoc', models.CharField(max_length=20)),
                ('phong_hoc', models.CharField(blank=True, max_length=50)),
                ('lich_hoc', models.CharField(blank=True, max_length=120)),
                ('si_so_toi_da', models.PositiveSmallIntegerField(default=60)),
                ('trang_thai', models.CharField(choices=[('OPEN', 'Dang mo'), ('CLOSED', 'Da dong')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='students.course')),
                ('giang_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-nam_hoc', '-hoc_ky', 'ma_lop_hp'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_hoc', models.DateField()),
                ('trang_thai', models.CharField(choices=[('PRESENT', 'Co mat'), ('ABSENT', 'Vang'), ('LATE', 'Di muon'), ('EXCUSED', 'Co phep')], default='PRESENT', max_length=20)),
                ('ghi_chu', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_updates', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.classroom')),
            ],
            options={
                'ordering': ['-ngay_hoc', 'enrollment__student__ma_sv'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='students.classroom'),
        ),
        migrations.RunPython(backfill_classroom_for_enrollments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', False)), fields=('student', 'classroom'), name='uniq_student_classroom'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('classroom', 'enrollment', 'ngay_hoc'), name='uniq_attendance_per_session'),
        ),
    ]
